setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
name: elk02
metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
    #- "network_summary"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["https://10.0.2.15:9200"]

  # Protocol - either `http` (default) or `https`.
  protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "elastic"
  password: "onw06_8uvZjvZWpotiGk"
  ssl.verification_mode: "none"

processors:
  - add_docker_metadata: 
      host: "unix:///var/run/docker.sock"
